dist: trusty
language: rust
services: docker
sudo: required

# TODO This is the Rust channel that build jobs will use by default but can be
# overridden on a case by case basis down below
rust: stable

env:
  global:
    # TODO Update this to match the name of your project.
    - CRATE_NAME=profiv

    # TODO This is the channel that will be used to produce binary releases
    - DEPLOY_VERSION=stable

    # default job
    - TARGET=x86_64-unknown-linux-gnu

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    # - env: TARGET=i686-unknown-linux-musl
    # - env: TARGET=x86_64-unknown-linux-gnu  # this is the default job
    #- env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Other architectures
    #- env: TARGET=aarch64-unknown-linux-gnu
    #- env: TARGET=armv7-unknown-linux-gnueabihf
    #- env: TARGET=mips-unknown-linux-gnu
    #- env: TARGET=mips64-unknown-linux-gnuabi64
    #- env: TARGET=mips64el-unknown-linux-gnuabi64
    #- env: TARGET=mipsel-unknown-linux-gnu
    #- env: TARGET=powerpc-unknown-linux-gnu
    #- env: TARGET=powerpc64-unknown-linux-gnu
    #- env: TARGET=powerpc64le-unknown-linux-gnu
    #- env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  # TODO update `api_key.secure`
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt GH_TOKEN=0123456789012345678901234567890123456789`
  # - Paste the output down here
  api_key:
    secure: I9OyeD9Ct5F6I9Wx7w+/TEzKnxGCbCxTvtXFt8j4oj4JwIqVfTDJGFYjP76vjST9cQFXN4zWj3/xirFPByiuuvyzipsGE4eOQ2dTShuHVExu8OuDmdO/OT6O66dQbTA2JbWKlwES0WJ634L35yFqKgnaUBX60xrhlLzjtxiklCQF/8AsTO5bllOsCie/H1HoObmqNJATkuwR5lptYV3mh5BhgjfJBPCD752Z5R7Q5vpXuBJMwjvbC0mmvMWLJrvJplZPdJbbL9VOU24FVEoWhu1XF+HvlNsaHZE00kMBu0rPlp5VixottDSLpqsYyxThDE8zxvhDO2V83GaVTjqHTUf7JCkhYakexBFCv7wPodgNPzjYzDXneqG5hi5hp02F63XNHDs+4biJKrQDSeED2hIvpITmpyy09Pu7y8sgJMIWlMwOh/R4DI/pEwWwigDFI1b1nUSD7kYGTYJqOm4qTo7tbAG0fKQjLwUJ0ICd1kw2sg1iXgGy9u1EdR4FJjRscbBS7ozttmWGv0KBxxeymt+Ju0FKJ0ItmeUaU8qFrckA+Ag2s7kudvcnBJ82nn6TniDzCQ2ps2HQPYCGo9rPoToYAD/vBhzrHElF2WQuEkbq1vT6DVBynOiKP7qggrcPHU/Vierv+j3AwMIWPXmFR8225iPbIa4uq8AOXPLUsS4=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = $DEPLOY_VERSION
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
