[package]
name = "ghcprof"
version = "0.1.0"
description = "Parser for GHC .prof files"
authors = ["Alfredo Di Napoli <alfredo.dinapoli@gmail.com>"]

[dependencies.nom]
version = "=2.0.1"
features = ["verbose-errors"]